drop table mvc_fact;
CREATE TABLE MVC_FACT(
	COLLISION_ID VARCHAR(7) PRIMARY KEY,
	CRASH_DATE DATE NOT NULL,
	CRASH_TIME TIME(7) NOT NULL,
	BOROUGH VARCHAR(13) NOT NULL,
	ZIPCODE CHAR(5)  NOT NULL,
	LATITUDE DECIMAL(8,6) NULL,
	LONGITUDE DECIMAL(9,6) NULL,
	LOCATION VARCHAR(50) NULL, -- TRIGGER UPDATE: LAT + LONG
	PERSONS_INJURED INT DEFAULT 0,
	PERSONS_KILLED INT DEFAULT 0,
	PEDESTRIANS_INJURED INT DEFAULT 0,
	PEDESTRIANS_KILLED INT DEFAULT 0,
	CYCLIST_INJURED INT DEFAULT 0,
	CYCLIST_KILLED INT DEFAULT 0,
	MOTORIST_INJURED INT DEFAULT 0,
	MOTORIST_KILLED INT DEFAULT 0,
	CONTRIBUTING_FACTOR VARCHAR(max) DEFAULT 'UNSPECIFIED',
	VEHICLE_TYPE_CODE_1 VARCHAR(50) DEFAULT 'UNSPECIFIED',
	CONSTRAINT CK_BOROUGH CHECK (BOROUGH IN ('MANHATTAN','BROOKLYN','QUEENS','STATEN ISLAND','BRONX','UNSPECIFIED')),
);

WITH MVC_TC AS (
	SELECT 
		raw_collisions.COLLISION_ID,
		raw_collisions.CRASH_DATE,
		raw_collisions.CRASH_TIME,
		CASE WHEN raw_collisions.BOROUGH IS NULL THEN 'UNSPECIFIED' ELSE BOROUGH END AS BOROUGH,
		CASE WHEN raw_collisions.ZIP_CODE IS NULL THEN '00000' ELSE ZIP_CODE END AS ZIP_CODE, 
		CASE WHEN raw_collisions.LATITUDE IS NULL THEN 0.0 ELSE raw_collisions.LATITUDE END AS LATITUDE,
		CASE WHEN raw_collisions.LONGITUDE IS NULL THEN 0.0 ELSE raw_collisions.LONGITUDE END AS LONGITUDE,
		CASE WHEN raw_collisions.LOCATION IS NULL THEN 'UNSPECIFIED' ELSE raw_collisions.LOCATION END AS LOCATION,
		raw_collisions.NUMBER_OF_PERSONS_INJURED,
		raw_collisions.NUMBER_OF_PERSONS_KILLED,
		raw_collisions.NUMBER_OF_PEDESTRIANS_INJURED,
		raw_collisions.NUMBER_OF_PEDESTRIANS_KILLED,
		raw_collisions.NUMBER_OF_CYCLIST_INJURED,
		raw_collisions.NUMBER_OF_CYCLIST_KILLED,
		raw_collisions.NUMBER_OF_MOTORIST_INJURED,
		raw_collisions.NUMBER_OF_MOTORIST_KILLED,
		raw_collisions.CONTRIBUTING_FACTOR_VEHICLE_1,
		raw_collisions.VEHICLE_TYPE_CODE_1
	FROM raw_collisions
	)
INSERT INTO MVC_FACT
SELECT 
	MVC_TC.COLLISION_ID,
	MVC_TC.CRASH_DATE,
	MVC_TC.CRASH_TIME,
	MVC_TC.BOROUGH,
	MVC_TC.ZIP_CODE,
	MVC_TC.LATITUDE,
	MVC_TC.LONGITUDE,
	MVC_TC.LOCATION,
	MVC_TC.NUMBER_OF_PERSONS_INJURED,
	MVC_TC.NUMBER_OF_PERSONS_KILLED,
	MVC_TC.NUMBER_OF_PEDESTRIANS_INJURED,
	MVC_TC.NUMBER_OF_PEDESTRIANS_KILLED,
	MVC_TC.NUMBER_OF_CYCLIST_INJURED,
	MVC_TC.NUMBER_OF_CYCLIST_KILLED,
	MVC_TC.NUMBER_OF_MOTORIST_INJURED,
	MVC_TC.NUMBER_OF_MOTORIST_KILLED,
	MVC_TC.CONTRIBUTING_FACTOR_VEHICLE_1,
	MVC_TC.VEHICLE_TYPE_CODE_1
FROM MVC_TC;

-- ROWS WHERE LOCATION CONTAINS LONGITUDE, HOWEVER LONGITUDE COLUMN DOESNT CONTAIN THE SAME DATA
SELECT * FROM MVC_FACT
WHERE LATITUDE != 0.0
AND LONGITUDE = 0.0;

UPDATE MVC_FACT SET LONGITUDE =  TRIM(')' FROM RIGHT(location,6))
WHERE LATITUDE != 0.0
AND LONGITUDE = 0.0;


SELECT VEHICLE_TYPE_CODE_1,
ROUND(((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100,2) AS percentage,
COUNT(*) as '# of occurences',
SUM(ROUND(((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100,2)) over (order by ((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100 DESC) as running_total,
ROW_NUMBER() over (order by Count(*) desc) as rn
FROM MVC_FACT
GROUP BY VEHICLE_TYPE_CODE_1;

with cte as (
SELECT VEHICLE_TYPE_CODE_1,
ROUND(((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100,2) AS percentage,
COUNT(*) as '# of occurences',
SUM(ROUND(((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100,2)) over (order by ((COUNT(*)*1.0)/(SELECT COUNT(*) FROM MVC_FACT))*100 DESC) as running_total,
ROW_NUMBER() over (order by Count(*) desc) as rn
FROM MVC_FACT
GROUP BY VEHICLE_TYPE_CODE_1
)
SELECT *,
CASE WHEN running_total <= 95.5 THEN 'TOP 95.5%' ELSE 'OTHER' END AS 'SUB GROUP'
FROM CTE;

--Bus
SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%bus%' 

update MVC_FACT set VEHICLE_TYPE_CODE_1 = 'Bus'
where COLLISION_ID in 
(SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%bus%' )
--Sedan
SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%sedan%' 

update MVC_FACT set VEHICLE_TYPE_CODE_1 = 'Sedan'
where COLLISION_ID in 
(SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%sedan%' )
--Suv
SELECT COLLISION_ID FROM MVC_FACT
where Lower(vehicle_type_code_1) LIKE '%suv%'
or
Lower(vehicle_type_code_1) LIKE '%station wagon%'
or
Lower(vehicle_type_code_1)LIKE '%sport utility%'

update MVC_FACT set VEHICLE_TYPE_CODE_1 = 'SUV'
where COLLISION_ID in 
(SELECT COLLISION_ID FROM MVC_FACT
where Lower(vehicle_type_code_1) LIKE '%suv%'
or
Lower(vehicle_type_code_1) LIKE '%station wagon%'
or
Lower(vehicle_type_code_1)LIKE '%utility vehicle%')
--van
SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%van%' 

update MVC_FACT set VEHICLE_TYPE_CODE_1 = 'Van'
where COLLISION_ID in 
(SELECT COLLISION_ID FROM MVC_FACT
WHERE LOWER(VEHICLE_TYPE_CODE_1) LIKE '%van%' )
-- unknown
SELECT COLLISION_ID FROM MVC_FACT
where Lower(vehicle_type_code_1) LIKE '%unknown%'
or VEHICLE_TYPE_CODE_1 is null;

update MVC_FACT set VEHICLE_TYPE_CODE_1 = 'Unknown'
where COLLISION_ID in 
(SELECT COLLISION_ID FROM MVC_FACT
where Lower(vehicle_type_code_1) LIKE '%unknown%'
or VEHICLE_TYPE_CODE_1 is null)
