--Collision Volume
--Total collisions
SELECT COUNT(*) FROM MVC_FACT;
--Human Impact
--Persons Injured
SELECT
SUM(PERSONS_INJURED) 'Total Persons Injured',
SUM(PEDESTRIANS_INJURED) 'Total Pedestrians Injured',
SUM(CYCLIST_INJURED) 'Total Cyclist Injured',
SUM(MOTORIST_INJURED) 'Total Motorist Injured'
FROM MVC_FACT;
--Persons Killed
SELECT
SUM(PERSONS_KILLED) 'Total Persons Killed',
SUM(PEDESTRIANS_KILLED) 'Total Pedestrians Killed',
SUM(CYCLIST_KILLED) 'Total Cyclist Killed',
SUM(MOTORIST_KILLED) 'Total Motorist Killed'
FROM MVC_FACT;

--Fatal Collision Rate
SELECT SUM(CASE WHEN PERSONS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS 'Fatal Collision Rate' FROM MVC_FACT
--Fatal Collision per 100 collisions
SELECT
((SELECT SUM(PERSONS_KILLED*1.0 ) FROM MVC_FACT)/ COUNT(*))*100 AS 'Fatal Collision Rate' FROM MVC_FACT; 

--Severity Metrics
--Average Injured per collision
SELECT SUM(CASE WHEN PERSONS_INJURED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS 'Average Injured per Collision' FROM MVC_FACT
--Average Killed per collision
SELECT AVG(PERSONS_KILLED*1.0) AS 'Average Killed per Collision' FROM MVC_FACT;

-- MOST PEOPLE KILLED BY YEAR
SELECT YEAR(CRASH_DATE) 'YEAR',
SUM(PERSONS_KILLED) 'TOTAL KILLED',
DENSE_RANK() OVER (ORDER BY SUM(PERSONS_KILLED) DESC) AS 'RANK'
FROM MVC_FACT
GROUP BY YEAR(CRASH_DATE) 
ORDER BY SUM(PERSONS_KILLED) DESC

select top 100 PERSONS_INJURED, PEDESTRIANS_INJURED, CYCLIST_INJURED, MOTORIST_INJURED from MVC_FACT
where PERSONS_INJURED > 1;

-- Total Fatalities per year

SELECT YEAR(CRASH_DATE) 'Year',
SUM(PERSONS_KILLED) 'Total Fatalities per year',
SUM(PERSONS_INJURED)  FROM MVC_FACT
GROUP BY YEAR(CRASH_DATE)
ORDER BY YEAR(CRASH_DATE);

-- Fatal Collision Rate by Borough
SELECT 
BOROUGH,
SUM(CASE WHEN PERSONS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) 'Fatal Collision Rate'
FROM MVC_FACT
WHERE BOROUGH != 'UNSPECIFIED'
GROUP BY BOROUGH
order by 'Fatal Collision Rate' DESC;

-- Fatal Collision Rate by Year
SELECT 
YEAR(CRASH_DATE) 'Year',
COUNT(*) '# of Collisions',
SUM(PERSONS_KILLED) '# of People Killed',
SUM(CASE WHEN PERSONS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) 'Fatal Collision Rate'
FROM MVC_FACT
GROUP BY YEAR(CRASH_DATE) 
order by YEAR(CRASH_DATE);


-- Fatal Collision Rate at Night, compared to the Day
SELECT
CASE WHEN DATEPART(HOUR,CRASH_TIME) BETWEEN 6 AND 18 THEN 'Day' ELSE 'Night' END as Time_of_Day,
SUM(CASE WHEN PERSONS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) Fatal_Collision_Rate
FROM MVC_FACT
GROUP BY 
CASE WHEN DATEPART(HOUR,CRASH_TIME) BETWEEN 6 AND 18 THEN 'Day' ELSE 'Night'
END;

--weekends vs weekdays

SELECT
	COUNT(*) AS TOTAL_COLLISIONS,
	SUM(CASE WHEN PERSONS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) Fatal_Collision_Rate,
	CASE WHEN DATENAME(W,CRASH_DATE) IN ('Saturday', 'Sunday') THEN 'WEEKEND' ELSE 'WEEKDAY' END AS WD
FROM MVC_FACT
	GROUP BY CASE WHEN DATENAME(W,CRASH_DATE) IN ('Saturday', 'Sunday') THEN 'WEEKEND' ELSE 'WEEKDAY' END;


-- pivot

SELECT * FROM
(SELECT YEAR(CRASH_DATE) AS YR,
MONTH(CRASH_DATE) AS MH,
COUNT(COLLISION_ID) AS TOT FROM MVC_FACT
GROUP BY YEAR(CRASH_DATE), MONTH(CRASH_DATE)) AS SUB
PIVOT
(MAX(TOT)
FOR MH IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])
) AS PVT

-- # of Collisions per year
SELECT 
YEAR(CRASH_DATE) AS YEAR,
COUNT(*) AS Total_Collisions
FROM raw_collisions
GROUP BY YEAR(CRASH_DATE)
ORDER BY YEAR(CRASH_DATE)

-- GROWTH RATE YTD
WITH CTE AS(
	SELECT 
		YEAR(CRASH_DATE) AS YEAR,
		COUNT(*) AS Total_Collisions,
		lag(COUNT(*)*1.0 ) OVER (ORDER BY YEAR(CRASH_DATE)) AS PREV_YEAR_COLLISIONS
	FROM raw_collisions
	GROUP BY YEAR(CRASH_DATE)
)
SELECT 
	YEAR,
	TOTAL_COLLISIONS,
	TOTAL_COLLISIONS - PREV_YEAR_COLLISIONS AS GROWTH,
	ROUND((TOTAL_COLLISIONS - PREV_YEAR_COLLISIONS)*100.0/PREV_YEAR_COLLISIONS,2) AS GROWTH_RATE
	FROM CTE

-- Are fatalities going up or down year over year?
--Need: Fatalities per year

WITH CTE AS
(
	SELECT
		YEAR(CRASH_DATE) AS YEAR,
		SUM(PERSONS_KILLED) AS TOTAL_KILLED_PER_YEAR,
		LAG(SUM(PERSONS_KILLED)*1.0) OVER (ORDER BY YEAR(CRASH_DATE)) AS PREV_YEAR_KILLED
	FROM MVC_FACT
		GROUP BY YEAR(CRASH_DATE)
)
SELECT
	YEAR,
	TOTAL_KILLED_PER_YEAR,
	ROUND(((TOTAL_KILLED_PER_YEAR - PREV_YEAR_KILLED)/PREV_YEAR_KILLED)*100,2) AS GROWTH_RATE
FROM CTE
WHERE YEAR != 2026;

--An assessment of pedestrian, cyclist, and motorist injury and fatality exposure.

SELECT 
	BOROUGH,
	SUM(CASE WHEN PEDESTRIANS_INJURED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS PEDESTRIAN_INJURY_RATE,
	SUM(CASE WHEN PEDESTRIANS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS PEDESTRIAN_FATALITY_RATE,
	SUM(CASE WHEN CYCLIST_INJURED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS CYCLIST_INJURY_RATE,
	SUM(CASE WHEN CYCLIST_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS CYCLIST_FATALITY_RATE,
	SUM(CASE WHEN MOTORIST_INJURED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS MOTORIST_INJURY_RATE,
	SUM(CASE WHEN MOTORIST_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS MOTORIST_FATALITY_RATE
FROM MVC_FACT
	WHERE BOROUGH != 'UNSPECIFIED'
	GROUP BY BOROUGH
	
	
--Injury Percentage
SELECT 
	SUM(PEDESTRIANS_INJURED*1.0)/SUM(PERSONS_INJURED),
	SUM(CYCLIST_INJURED*1.0)/SUM(PERSONS_INJURED),
	SUM(MOTORIST_INJURED*1.0)/SUM(PERSONS_INJURED)
FROM MVC_FACT

--Where are pedestrians most at risk
SELECT 
	BOROUGH,
	SUM(CASE WHEN PEDESTRIANS_INJURED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS PEDESTRIAN_INJURY_RATE,
	SUM(CASE WHEN PEDESTRIANS_KILLED > 0 THEN 1.0 ELSE 0 END) / COUNT(*) AS PEDESTRIAN_FATALITY_RATE
FROM MVC_FACT
	WHERE BOROUGH != 'UNSPECIFIED'
	GROUP BY BOROUGH
	order by PEDESTRIAN_INJURY_RATE desc, PEDESTRIAN_FATALITY_RATE desc 

--Top 10 dangerous zipcodes
SELECT
	ZIPCODE,
	COUNT(*) AS TOTAL_COLLISIONS,
	SUM(CASE WHEN PERSONS_INJURED > 0 THEN 1.0 ELSE 0 END)/COUNT(*) AS INJURY_RATE
FROM MVC_FACT
	WHERE ZIPCODE != 0
	GROUP BY ZIPCODE
	ORDER BY TOTAL_COLLISIONS DESC, INJURY_RATE DESC;

SELECT CONTRIBUTING_FACTOR, COUNT(*) FROM MVC_FACT
GROUP BY CONTRIBUTING_FACTOR
ORDER BY COUNT(*) DESC